In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5, 4)
print(x)

# torch로 [5, 4]인 2D 텐서를 제작한다.

tensor([[8.4490e-39, 1.0102e-38, 9.0919e-39, 1.0102e-38],
        [8.9082e-39, 8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 1.0561e-38, 1.0194e-38]])


In [3]:
torch.ones(3, 3)
# 1, 이 들어가있는 [3, 3] 2D 텐서를 제작한다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)
# 0.이 들어가있는 [2] 1D텐서를 제작한다.

tensor([0., 0.])

In [5]:
torch.rand(5, 6)

# 랜덤값을 넣어 행렬 제작

tensor([[0.6216, 0.8053, 0.1787, 0.1574, 0.9467, 0.6588],
        [0.4319, 0.0714, 0.7518, 0.1359, 0.2044, 0.7270],
        [0.3895, 0.0108, 0.6618, 0.6111, 0.7469, 0.4706],
        [0.0175, 0.9627, 0.9145, 0.8775, 0.8119, 0.7034],
        [0.7258, 0.3661, 0.1531, 0.6214, 0.3725, 0.9400]])

In [6]:
l = [13, 4]
r = np.array([4, 56, 7])

In [7]:
torch.tensor(l)
# 텐서로 변환

tensor([13,  4])

In [8]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [9]:
x.size()

torch.Size([5, 4])

In [10]:
type(x)

torch.Tensor

In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.5582, 0.1851],
        [0.6802, 0.3508]])
tensor([[0.6064, 0.0858],
        [0.9353, 0.1505]])


In [12]:
x+y

tensor([[1.1646, 0.2709],
        [1.6155, 0.5014]])

In [13]:
torch.add(x, y)

tensor([[1.1646, 0.2709],
        [1.6155, 0.5014]])

In [14]:
y.add(x)

tensor([[1.1646, 0.2709],
        [1.6155, 0.5014]])

In [15]:
y.add_(x)
# _은 인플레이션으로 _를 쓰면 y에 x를 더한 값을 y에 넣는다는 의미이다.

tensor([[1.1646, 0.2709],
        [1.6155, 0.5014]])

In [16]:
y

tensor([[1.1646, 0.2709],
        [1.6155, 0.5014]])

In [17]:
x = torch.rand(8,8)
print(x)

tensor([[0.4319, 0.1241, 0.9262, 0.5066, 0.1399, 0.6572, 0.2569, 0.8063],
        [0.9258, 0.6073, 0.8121, 0.6891, 0.6295, 0.0356, 0.5538, 0.6404],
        [0.0439, 0.7715, 0.8703, 0.7372, 0.2647, 0.3792, 0.8965, 0.6403],
        [0.8646, 0.4206, 0.5566, 0.6054, 0.1212, 0.6610, 0.1977, 0.7310],
        [0.9278, 0.9656, 0.3551, 0.7926, 0.1518, 0.7322, 0.7339, 0.4582],
        [0.7861, 0.9246, 0.0970, 0.0951, 0.2627, 0.2570, 0.5802, 0.9471],
        [0.1371, 0.9488, 0.0101, 0.5327, 0.0598, 0.0524, 0.6888, 0.2439],
        [0.6494, 0.5221, 0.6720, 0.0967, 0.0872, 0.0799, 0.3777, 0.5258]])


In [19]:
bf = x.view(64) # 64개를 쭉 나열하겠다.
af = x.view(8,8)

In [21]:
print('x.view(64)를 한 값은 \n', bf.ndim)
print('x.view(8,8)를 한 값은 \n', af.ndim)
# 차원도 다르다는 것을 알 수 있다.

x.view(64)를 한 값은 
 1
x.view(8,8)를 한 값은 
 2


In [22]:
x.view(-1, 16)

# -1을 넣으면 알아서 계산이 된다!!

tensor([[0.4319, 0.1241, 0.9262, 0.5066, 0.1399, 0.6572, 0.2569, 0.8063, 0.9258,
         0.6073, 0.8121, 0.6891, 0.6295, 0.0356, 0.5538, 0.6404],
        [0.0439, 0.7715, 0.8703, 0.7372, 0.2647, 0.3792, 0.8965, 0.6403, 0.8646,
         0.4206, 0.5566, 0.6054, 0.1212, 0.6610, 0.1977, 0.7310],
        [0.9278, 0.9656, 0.3551, 0.7926, 0.1518, 0.7322, 0.7339, 0.4582, 0.7861,
         0.9246, 0.0970, 0.0951, 0.2627, 0.2570, 0.5802, 0.9471],
        [0.1371, 0.9488, 0.0101, 0.5327, 0.0598, 0.0524, 0.6888, 0.2439, 0.6494,
         0.5221, 0.6720, 0.0967, 0.0872, 0.0799, 0.3777, 0.5258]])

In [24]:
# 텐서에서 넘파이로 변환

y = x.numpy()

In [25]:
type(y)

numpy.ndarray

In [26]:
# 스칼라일때만 가능한 값 변환

x = torch.ones(1)

In [27]:
x

tensor([1.])

In [28]:
x.item()

1.0