In [1]:
import torch
import torch.nn as nn


In [2]:
torch.manual_seed(1)

In [3]:
# 데이터

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
model = nn.Linear(1, 1)
# (input_dim, output_dim)이 매개변수이다.

In [5]:
# 가중치 W와 편향 b값을 parameters()함수로 알아볼 수 있다.
print(list(model.parameters()))
# 첫번째 값이 W이고 두번째 값이 b값이다.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.01)

In [16]:
import torch.nn.functional as F

epochs = 20

for epoch in range(epochs+1):
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1 == 0:
        print("epoch : {}/{}, paramiter : {}, cost : {:.6f}".format(epoch, epochs, prediction, cost.item()))

epoch : 0/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 1/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 2/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 3/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 4/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 5/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 6/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 7/20, paramiter : tensor([[2.0000],
        [4.0000],
        [6.0000]], grad_fn=<AddmmBackward>), cost : 0.000000
epoch : 8/20, pa

In [17]:
new_var = torch.FloatTensor([4.0])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 : ", pred_y)

훈련 후 입력이 4일 때의 예측값 :  tensor([8.0000], grad_fn=<AddBackward0>)


In [18]:
print(list(model.parameters()))

[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([8.7014e-06], requires_grad=True)]


In [20]:
# 다중 선형 회귀

x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98,100],
                            [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [21]:
model = nn.Linear(3, 1)

In [22]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [23]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [26]:
epochs = 20000

for epoch in range(epochs+1):
    prediction = model(x_train)
    
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 1000 == 0:
        print("epoch : {}/{}, cost : {}".format(epoch, epochs, cost))

epoch : 0/20000, cost : 2.213616132736206
epoch : 1000/20000, cost : 1.3585500717163086
epoch : 2000/20000, cost : 0.8610031008720398
epoch : 3000/20000, cost : 0.5713972449302673
epoch : 4000/20000, cost : 0.4027414917945862
epoch : 5000/20000, cost : 0.3044343590736389
epoch : 6000/20000, cost : 0.24704840779304504
epoch : 7000/20000, cost : 0.2134844809770584
epoch : 8000/20000, cost : 0.19376316666603088
epoch : 9000/20000, cost : 0.18211719393730164
epoch : 10000/20000, cost : 0.17517493665218353
epoch : 11000/20000, cost : 0.17097605764865875
epoch : 12000/20000, cost : 0.16837558150291443
epoch : 13000/20000, cost : 0.16671404242515564
epoch : 14000/20000, cost : 0.16561424732208252
epoch : 15000/20000, cost : 0.1648322343826294
epoch : 16000/20000, cost : 0.16425660252571106
epoch : 17000/20000, cost : 0.16379818320274353
epoch : 18000/20000, cost : 0.1634138971567154
epoch : 19000/20000, cost : 0.16307833790779114
epoch : 20000/20000, cost : 0.16277337074279785


In [27]:
our = torch.FloatTensor([[73, 80, 75]])

In [29]:
my=model(our)
print("예측값 : ", my)

예측값 :  tensor([[151.6221]], grad_fn=<AddmmBackward>)


In [30]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0707, 0.5358, 0.4032]], requires_grad=True), Parameter containing:
tensor([0.3596], requires_grad=True)]
