In [12]:
import torch
import torch.optim as optim

In [4]:
x_train = torch.Tensor([1,2,3,4,5,6])
y_train = torch.Tensor([2, 4, 6, 8, 10, 12])

In [5]:
print(x_train)

tensor([1., 2., 3., 4., 5., 6.])


In [6]:
w = torch.zeros(1, requires_grad = True)

In [7]:
print(w)

tensor([0.], requires_grad=True)


In [8]:
b = torch.zeros(1, requires_grad=True)

print(b)

tensor([0.], requires_grad=True)


In [14]:
epochs = 2000
optimizer = optim.SGD([w, b], lr=0.01)

In [17]:
for epoch in range(epochs+1):
    hypothesis = x_train * w + b
    
    cost = torch.mean((hypothesis - y_train) ** 2) # 평균 제곱 오차
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    
    if epoch % 100 == 0:
       print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 1.300, b: 0.299 Cost: 13.024631
Epoch  100/2000 W: 1.929, b: 0.304 Cost: 0.017912
Epoch  200/2000 W: 1.951, b: 0.211 Cost: 0.008621
Epoch  300/2000 W: 1.966, b: 0.146 Cost: 0.004150
Epoch  400/2000 W: 1.976, b: 0.102 Cost: 0.001997
Epoch  500/2000 W: 1.984, b: 0.070 Cost: 0.000961
Epoch  600/2000 W: 1.989, b: 0.049 Cost: 0.000463
Epoch  700/2000 W: 1.992, b: 0.034 Cost: 0.000223
Epoch  800/2000 W: 1.995, b: 0.024 Cost: 0.000107
Epoch  900/2000 W: 1.996, b: 0.016 Cost: 0.000052
Epoch 1000/2000 W: 1.997, b: 0.011 Cost: 0.000025
Epoch 1100/2000 W: 1.998, b: 0.008 Cost: 0.000012
Epoch 1200/2000 W: 1.999, b: 0.005 Cost: 0.000006
Epoch 1300/2000 W: 1.999, b: 0.004 Cost: 0.000003
Epoch 1400/2000 W: 1.999, b: 0.003 Cost: 0.000001
Epoch 1500/2000 W: 2.000, b: 0.002 Cost: 0.000001
Epoch 1600/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1700/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1800/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1900/2000 W: 2.000, b: 0.000 Cost: 0.000000